version: "3.8"
services:
  servidor:
    build:
      context: ${CONTEXTO}
      dockerfile: /home/andres/hlc/develop/HLC-24-25/Caronte/proyectos/webcvalera/Dockerfile
      args: 
        - CONTEXT=${CONTEXTO}
        - TZ=${TZ}
        - PROYECTO=${PROYECTO}
        - AUTOR=${AUTOR}
        - GITHUB=${GITHUB}
    image: ${AUTOR}/webcvalera:1.0
    container_name: ${PROYECTO}
    hostname: ${HOSTNAME}
    env_file:
      - ./.env
    environment:
      - USUARIO=${USUARIO}
      - PASSWORD=${PASSWD}
    ports:
      - "${PORT_ORIGEN}:80"
      - "3000:3000"
    volumes:
    - ./logs:/root/logs
    - ./html:/var/www/html
    networks:
      netcaronte:
        ipv4_address: 172.120.10.6


networks:
  netcaronte:
    ipam:
      driver: default
      config:
        - subnet: 172.120.10.0/24