apiVersion: v1
kind: Pod
metadata:
  name: nginx3
  labels:
    zone: prod
    version: v1
spec:
  containers:
  - name: nginx3
    image: lusardi1943/webcvalera:latest
    envFrom:
    - configMapRef:
        name: app-env
